### ISSUE TITLE
Add share buttons to template.html

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#12]
+ twitter: https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview

+ facebook: https://developers.facebook.com/docs/plugins/share-button/

+ other?

**Comment by jalbertbowden** [comment]
i'm so old, i'm sure there are platforms we should adopt for this, we just need to look into it.
tik tok? is that just videos?
we can loop back later I reckon; go with the big two first.

**Comment by jalbertbowden** [comment]
do we want to create a twitter account? thinking to far ahead?

**Comment by philshem** [comment]
done, also linkedin. but not so neat.
