### ISSUE TITLE
CO2 birthday badges: allow shields.io style of badges

### ISSUE THREAD

**Issue by gonzalocasas** [co2birthdate/website#13]
There could be two (at least) types of badges to show your co2 birthday in other places:
* co2 ppm badge: just showing the ppm value on the selected day
* percent over today (or percentage increase until today): eg `I was born with "18.5% less co2 ppm"` or the opposite, `"22% more co2 ppm" since I was born`

**Comment by philshem** [comment]
really cool idea gonzalo!

something like this

    https://img.shields.io/static/v1?label=born 333.3 ppm CO%E2%82%82&message=today we are 28%25 higher&color=green

[!shield](https://img.shields.io/static/v1?label=born 333.3 ppm CO%E2%82%82&message=today we are 28%25 higher&color=green)

**Comment by gonzalocasas** [comment]
👍

**Comment by jalbertbowden** [comment]
these are cool. great idea.

**Comment by jalbertbowden** [comment]
do we want to use these vs. the circles/sizes mentioned in the other issue?

**Comment by philshem** [comment]
I prefer shields

**Comment by jalbertbowden** [comment]
ok. working on this now

**Comment by jalbertbowden** [comment]
these are implemented with basic styles. not sure if you wanted these or the other options that they offer.

**Comment by jalbertbowden** [comment]
also, can you show me where the png versions are/how they are more complicated?
not arguing, but maybe there's a way to get both to play nicely.

**Comment by jalbertbowden** [comment]
also wondering if we should hack on an extra badge piece, in another color, to show what the value today is?

**Comment by jalbertbowden** [comment]
![shields io-hack](https://user-images.githubusercontent.com/46432/93166873-5e6b6500-f6ed-11ea-9ff3-8bbe8a1a03f7.png)
hacked this out tonight.

**Comment by philshem** [comment]
wow looks great!

**Comment by philshem** [comment]
shield.svg now exists in every date folder, for easier sharing and re-use.
