### ISSUE TITLE
Remaining changes to website

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#17]
Things are looking good. I see the following small open issues before we start to publicize:

+ accept 1 digit month and day (if possible)

- [ ] 

+ use a common `footer.html` for both index.html and `1980/12/31/index.html` (just so we have one place to make changes)

+ (ps) need to cleanup the dataops/readme to better explain the data methodology

+ I like the shields, but would be cool for people to be able to get the svg to use on their own site... In the meantime I have put back the original text results, which are easier to read

+ placement of the 3 sharing buttons can be cleaned up

+ adding actual URL path to the sharing buttons (currently it shares only the main page)

**Comment by philshem** [comment]
Also, the view from mobile from the main index.html is not very good.

**Comment by philshem** [comment]
also there could be the case that the value went down (for example, june 01 2020). maybe we need to encode "higher" or "lower" somehow. it's an edge case

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by jalbertbowden** [comment]
thats a great point about edge case values.

i'd like to use a common header/footer across all the pages, but i wasn't sure how to define it/where to define it.
would it just be an html stub, like header.html?
sorry, just not familiar with python templating; but this is how I'd do it in PHP.

need to come back to the license year generation @ some point; sorry man, `document.write` is bad for performance and security. i think it may actually be a non-standard now.

would like to break the text in the input submit form control into two lines...i think thats going to require using input type="button" or just button type="submit". easy enough, but will need JS function to fire off. not sure what tradeoffs are with not using native submit, but I think we are in the clear here.

**Comment by philshem** [comment]
my bad about`document.write`. I'd just hardcode 2020

**Comment by jalbertbowden** [comment]
na, its not your bad. i appreciate the help! or on that level, my bad for not designing mobile-first.
i was much more paying attention to the functionality vs. style @ that point.
no worries man.

**Comment by philshem** [comment]
almost ready to go!

+ the sharing buttons don't show up in template.html, I think because I removed the html list elements. (I didn't like the bullet points before the icons.)
<img width="247" alt="image" src="https://user-images.githubusercontent.com/4997607/93569576-043efe00-f992-11ea-92ec-6088b882500a.png">

+ Any way to get the svg shields to be shareable?

**Comment by jalbertbowden** [comment]
got a lot of things to push today.
i do think there's a way to share the badges but probably need to circle back to that. it may take me a hot minute.

**Comment by jalbertbowden** [comment]
maybe here. lets come back to this after i do everything else:
https://web.archive.org/web/20200125162931/http://ramblings.mcpher.com:80/Home/excelquirks/gassnips/svgtopng

**Comment by jalbertbowden** [comment]
hashed out each pages url....it seems to be working. you can see the url variable its using in the page's content.
i'll remove that before we go live. just wanted it to be visible/easy to check atm.
this was done with this push: https://github.com/co2birthdate/website/commit/b9d3d855bc56ad15cc57d057ee43a61e98c42dda

**Comment by jalbertbowden** [comment]
cleaned up social sharing links here:
https://github.com/co2birthdate/website/commit/0132099a104122de593dffefcd42bbf4bccc2a98
of note: linkedin badge in ff in os x is different. i think its an entirely different image...haven't dove into it yet.
also, i added background colors to each social share button, to hide the jank as they load; this revealed the text they have hidden (ex, "Tweet", "Share") in white colored font. So I copied that approach, and made the text the same color as the background; this works for what we want, but this is horrible practice and not accessible. Just sharing.

**Comment by jalbertbowden** [comment]
svg to png functionality is implemented here:
https://github.com/co2birthdate/website/commit/71dff9499262aa9a0f9083808881efa351dfdabc

it needs touching up but i also have a few questions here:
it uses blob feature as img src attribute...is that sufficient for sharing? i think so, but i'm not 100%.
wondering if we can't just generate all of these on the server and point to that url?

**Comment by jalbertbowden** [comment]
the only things left are allowing one digit day/month and cleaning dataops/readme.

i've been tinkering with how to do the one digit and i can't grasp it mentally. maybe you can and you can help me.
script is relying on keydown to track what user has entered.
if user has entered more than one digit, it tries to validate it.
if we throw the validation on one digit, how do we differentiate between `1` and `12`?
or rather, how will the script know that the user wants to add another digit?
forcing two digit entry made this easier, but perhaps its the wrong approach.
i did some digging around but i can't find much on how to do what you want...not saying it is not possible, just not sure from my view at this moment.

**Comment by jalbertbowden** [comment]
i'd like to touch up the styles across the board, thats the only thing sticking out to me at the moment.

**Comment by philshem** [comment]
something with the sharing buttons has gone wrong

<img width="277" alt="image" src="https://user-images.githubusercontent.com/4997607/93760582-97836800-fc0c-11ea-8bec-883cfb22f375.png">

(the twitter link does not work, as well)

**Comment by philshem** [comment]
small thing but we should add link to explain ppm


maybe link this site?? https://www.climate.gov/news-features/understanding-climate/climate-change-atmospheric-carbon-dioxide

**Comment by jalbertbowden** [comment]
i just pulled to level up with the repo and the social buttons look fine on my end. you still seeing this?

**Comment by jalbertbowden** [comment]
i think explaining ppm is important. i was thinking maybe we need an about page?

**Comment by philshem** [comment]
Was thinking just a link to a readme

**Comment by jalbertbowden** [comment]
that works to

**Comment by jalbertbowden** [comment]
ok. so our last issue is firefox blocking facebook share.
from what i can gather, if you have tracking turned off in firefox, there is no way around this.
off the top of my head, i want to say if you are sharing on facebook, you are a facebook user and won't have tracking turned off. i realize that is making light of the situation/setting us up for failure.

**Comment by jalbertbowden** [comment]
3rd Party-less Social Sharing implemented here: https://github.com/co2birthdate/website/commit/3406d4a00acd848ab3ceebc3cc1973fe7782bbd6.
We probably want to go in and edit what the message(s) for the shares.

**Comment by jalbertbowden** [comment]
need to credit this noun project icon/designer.
dropping this here so we don't forget:
link 
By Matthew Exton 

https://thenounproject.com/term/link/1690/
