### ISSUE TITLE
Fix subscript in title

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#18]
<img width="190" alt="image" src="https://user-images.githubusercontent.com/4997607/93198357-34e22600-f74d-11ea-8b1a-62d1fdead6a5.png">

(both index.html and template.html)

**Comment by jalbertbowden** [comment]
index.html is fixed with this push: https://github.com/co2birthdate/website/commit/6575dba42c3a659f47596202f543ce06e451deff
