### ISSUE TITLE
tracking visits?

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#19]
One downside to GH pages is that there are no real traffic stats.

I'd prefer to not use google analytics. Do we want or need tracking?

**Comment by jalbertbowden** [comment]
its always interesting to me, but not necessarily.
definitely don't want to use Google; there are open source solutions and/or we can roll our own if we want...

**Comment by philshem** [comment]
Let’s skip it,, since users may be uploading their birthday which is personal

**Comment by jalbertbowden** [comment]
https://trackgit.com/

**Comment by philshem** [comment]
looks good!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
