### ISSUE TITLE
project name and website (?)

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#3]
Ideas go here:

+ co2birthdate

+ ...

**Comment by jalbertbowden** [comment]
birthdatec02 
birthdateco2 
co2birthdate

**Comment by jalbertbowden** [comment]
Possible TLDS:
.today
.weather
.org
.ca
.pm
.date
.day
.eco
.science

**Comment by philshem** [comment]
I bought

co2birth.date

and set up email forwarding from info@ to my email
