### ISSUE TITLE
building script from html templates

### ISSUE THREAD

**Issue by philshem** [co2birthdate/website#4]
As it now seems, HTML templates for each date will live in a individual folder. We will "build" each html page with the value of co2 on that date.

This means we probably need a simple build script, which:

1. reads the raw co2 data (json dict)
2. reads all html template files (glob)
3. writes co2 values from json dict to those html

It probably makes sense to have 2 branches in this repository, similar to static site builders. `main` branch is for the html templates and builder script (python) and the `gh-pages` branch is for the public html.

A github action can be configured to build the public html and push to `gh-pages` every time there is a change to the `main` branch.

**Comment by jalbertbowden** [comment]
Do you want to take a swing @ a skeleton build script? So that I can chop up the frontend into a template.
Sorry, I should have asked for this much earlier.

**Comment by philshem** [comment]
Yeah, I can write the build script. Point me to an html template file when ready.

**Comment by philshem** [comment]
I think this is done with https://github.com/co2birthdate/website/commit/9db60142b83587f8436a6ca52183a92951958b78
