### ISSUE TITLE
Icon/Favicon

### ISSUE THREAD

**Issue by jalbertbowden** [co2birthdate/website#5]

**Comment by philshem** [comment]
could we use this co2 glyph with proper attribution?

https://thenounproject.com/term/co2/2094260/

 
<img width="338" alt="image" src="https://user-images.githubusercontent.com/4997607/91689260-03ba0100-eb64-11ea-93f2-fee24eb8a396.png">

**Comment by jalbertbowden** [comment]
[co2 by Alfonso López-Sanz from the Noun Project)[https://thenounproject.com/term/co2/2094260/)  
You must add attribution:
Use the embedded attribution if the icon is larger than 100px.
Copy the attribution text below and include it in a bibliography or image caption, or on a physical item or its tag.
Learn More
Attribution text
co2 by Alfonso López-Sanz from the Noun Project

**Comment by jalbertbowden** [comment]
cropped 512x512 logo and converted that into a bunch of different favicons/sizes/etc.
